# Generated by Django 2.1.7 on 2020-07-25 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='products',
            name='item_code',
        ),
    ]
