# Generated by Django 2.1.7 on 2020-07-25 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_remove_shipments_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordershipments',
            old_name='Shipment',
            new_name='shipment',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='is_active',
        ),
    ]
